### ISSUE TITLE
Record task lifecycle

### ISSUE THREAD

**Issue by ryanchard** [funcx-faas/funcx-web-service#169]
We want to expose the current status of a task in terms of where it is in the lifecycle. This will require modifications to support tracking at the Web service, Forwarder, and Endpoints. Recorded states should include:

- [ ] Received
- [ ] Waiting for EP
- [ ] Waiting for worker
- [ ] Running
- [ ] Success/Failed

**Comment by yadudoc** [comment]
![Untitled presentation](https://user-images.githubusercontent.com/181489/87821355-5601c580-c835-11ea-8068-50dab63cc2b7.jpg)

https://docs.google.com/presentation/d/1YlXhAwWWY3TibJLRx3icgmLLlxflho5F8aEc70JouSE/edit?usp=sharing
